export const countries = {
  AFG: { name: "Afghanistan", flag: "https://flagcdn.com/w20/af.png" },
  ALB: { name: "Albania", flag: "https://flagcdn.com/w20/al.png" },
  DZA: { name: "Algeria", flag: "https://flagcdn.com/w20/dz.png" },
  AND: { name: "Andorra", flag: "https://flagcdn.com/w20/ad.png" },
  AGO: { name: "Angola", flag: "https://flagcdn.com/w20/ao.png" },
  ATG: { name: "Antigua and Barbuda", flag: "https://flagcdn.com/w20/ag.png" },
  ARG: { name: "Argentina", flag: "https://flagcdn.com/w20/ar.png" },
  ARM: { name: "Armenia", flag: "https://flagcdn.com/w20/am.png" },
  ABW: { name: "Aruba", flag: "https://flagcdn.com/w20/aw.png" },
  AUS: { name: "Australia", flag: "https://flagcdn.com/w20/au.png" },
  AUT: { name: "Austria", flag: "https://flagcdn.com/w20/at.png" },
  AZE: { name: "Azerbaijan", flag: "https://flagcdn.com/w20/az.png" },
  BHS: { name: "Bahamas", flag: "https://flagcdn.com/w20/bs.png" },
  BHR: { name: "Bahrain", flag: "https://flagcdn.com/w20/bh.png" },
  BGD: { name: "Bangladesh", flag: "https://flagcdn.com/w20/bd.png" },
  BRB: { name: "Barbados", flag: "https://flagcdn.com/w20/bb.png" },
  BLR: { name: "Belarus", flag: "https://flagcdn.com/w20/by.png" },
  BEL: { name: "Belgium", flag: "https://flagcdn.com/w20/be.png" },
  BLZ: { name: "Belize", flag: "https://flagcdn.com/w20/bz.png" },
  BEN: { name: "Benin", flag: "https://flagcdn.com/w20/bj.png" },
  BTN: { name: "Bhutan", flag: "https://flagcdn.com/w20/bt.png" },
  BOL: { name: "Bolivia", flag: "https://flagcdn.com/w20/bo.png" },
  BIH: { name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w20/ba.png" },
  BWA: { name: "Botswana", flag: "https://flagcdn.com/w20/bw.png" },
  BRA: { name: "Brazil", flag: "https://flagcdn.com/w20/br.png" },
  BRN: { name: "Brunei Darussalam", flag: "https://flagcdn.com/w20/bn.png" },
  BGR: { name: "Bulgaria", flag: "https://flagcdn.com/w20/bg.png" },
  BFA: { name: "Burkina Faso", flag: "https://flagcdn.com/w20/bf.png" },
  BDI: { name: "Burundi", flag: "https://flagcdn.com/w20/bi.png" },
  CPV: { name: "Cabo Verde", flag: "https://flagcdn.com/w20/cv.png" },
  KHM: { name: "Cambodia", flag: "https://flagcdn.com/w20/kh.png" },
  CMR: { name: "Cameroon", flag: "https://flagcdn.com/w20/cm.png" },
  CAN: { name: "Canada", flag: "https://flagcdn.com/w20/ca.png" },
  CYM: { name: "Cayman Islands", flag: "https://flagcdn.com/w20/ky.png" },
  CHL: { name: "Chile", flag: "https://flagcdn.com/w20/cl.png" },
  CHN: { name: "China", flag: "https://flagcdn.com/w20/cn.png" },
  COL: { name: "Colombia", flag: "https://flagcdn.com/w20/co.png" },
  CRI: { name: "Costa Rica", flag: "https://flagcdn.com/w20/cr.png" },
  HRV: { name: "Croatia", flag: "https://flagcdn.com/w20/hr.png" },
  CUB: { name: "Cuba", flag: "https://flagcdn.com/w20/cu.png" },
  CUW: { name: "Curaçao", flag: "https://flagcdn.com/w20/cw.png" },
  CYP: { name: "Cyprus", flag: "https://flagcdn.com/w20/cy.png" },
  CZE: { name: "Czech Republic", flag: "https://flagcdn.com/w20/cz.png" },
  CIV: { name: "Côte d'Ivoire", flag: "https://flagcdn.com/w20/ci.png" },
  DNK: { name: "Denmark", flag: "https://flagcdn.com/w20/dk.png" },
  DJI: { name: "Djibouti", flag: "https://flagcdn.com/w20/dj.png" },
  DMA: { name: "Dominica", flag: "https://flagcdn.com/w20/dm.png" },
  DOM: { name: "Dominican Republic", flag: "https://flagcdn.com/w20/do.png" },
  ECU: { name: "Ecuador", flag: "https://flagcdn.com/w20/ec.png" },
  EGY: { name: "Egypt", flag: "https://flagcdn.com/w20/eg.png" },
  SLV: { name: "El Salvador", flag: "https://flagcdn.com/w20/sv.png" },
  EST: { name: "Estonia", flag: "https://flagcdn.com/w20/ee.png" },
  SWZ: { name: "Eswatini", flag: "https://flagcdn.com/w20/sz.png" },
  FIN: { name: "Finland", flag: "https://flagcdn.com/w20/fi.png" },
  FRA: { name: "France", flag: "https://flagcdn.com/w20/fr.png" },
  GUF: { name: "French Guiana", flag: "https://flagcdn.com/w20/gf.png" },
  PYF: { name: "French Polynesia", flag: "https://flagcdn.com/w20/pf.png" },
  GAB: { name: "Gabon", flag: "https://flagcdn.com/w20/ga.png" },
  GMB: { name: "Gambia", flag: "https://flagcdn.com/w20/gm.png" },
  GEO: { name: "Georgia", flag: "https://flagcdn.com/w20/ge.png" },
  DEU: { name: "Germany", flag: "https://flagcdn.com/w20/de.png" },
  GHA: { name: "Ghana", flag: "https://flagcdn.com/w20/gh.png" },
  GIB: { name: "Gibraltar", flag: "https://flagcdn.com/w20/gi.png" },
  GRC: { name: "Greece", flag: "https://flagcdn.com/w20/gr.png" },
  GRL: { name: "Greenland", flag: "https://flagcdn.com/w20/gl.png" },
  GTM: { name: "Guatemala", flag: "https://flagcdn.com/w20/gt.png" },
  GUY: { name: "Guyana", flag: "https://flagcdn.com/w20/gy.png" },
  HTI: { name: "Haiti", flag: "https://flagcdn.com/w20/ht.png" },
  HND: { name: "Honduras", flag: "https://flagcdn.com/w20/hn.png" },
  HKG: { name: "Hong Kong", flag: "https://flagcdn.com/w20/hk.png" },
  HUN: { name: "Hungary", flag: "https://flagcdn.com/w20/hu.png" },
  ISL: { name: "Iceland", flag: "https://flagcdn.com/w20/is.png" },
  IND: { name: "India", flag: "https://flagcdn.com/w20/in.png" },
  IDN: { name: "Indonesia", flag: "https://flagcdn.com/w20/id.png" },
  IRN: { name: "Iran", flag: "https://flagcdn.com/w20/ir.png" },
  IRQ: { name: "Iraq", flag: "https://flagcdn.com/w20/iq.png" },
  IRL: { name: "Ireland", flag: "https://flagcdn.com/w20/ie.png" },
  ISR: { name: "Israel", flag: "https://flagcdn.com/w20/il.png" },
  ITA: { name: "Italy", flag: "https://flagcdn.com/w20/it.png" },
  JAM: { name: "Jamaica", flag: "https://flagcdn.com/w20/jm.png" },
  JPN: { name: "Japan", flag: "https://flagcdn.com/w20/jp.png" },
  JOR: { name: "Jordan", flag: "https://flagcdn.com/w20/jo.png" },
  KAZ: { name: "Kazakhstan", flag: "https://flagcdn.com/w20/kz.png" },
  KEN: { name: "Kenya", flag: "https://flagcdn.com/w20/ke.png" },
  XKX: { name: "Kosovo", flag: "https://flagcdn.com/w20/xk.png" },
  KWT: { name: "Kuwait", flag: "https://flagcdn.com/w20/kw.png" },
  LVA: { name: "Latvia", flag: "https://flagcdn.com/w20/lv.png" },
  LBN: { name: "Lebanon", flag: "https://flagcdn.com/w20/lb.png" },
  LSO: { name: "Lesotho", flag: "https://flagcdn.com/w20/ls.png" },
  LBR: { name: "Liberia", flag: "https://flagcdn.com/w20/lr.png" },
  LBY: { name: "Libya", flag: "https://flagcdn.com/w20/ly.png" },
  LIE: { name: "Liechtenstein", flag: "https://flagcdn.com/w20/li.png" },
  LTU: { name: "Lithuania", flag: "https://flagcdn.com/w20/lt.png" },
  LUX: { name: "Luxembourg", flag: "https://flagcdn.com/w20/lu.png" },
  MAC: { name: "Macao", flag: "https://flagcdn.com/w20/mo.png" },
  MDG: { name: "Madagascar", flag: "https://flagcdn.com/w20/mg.png" },
  MYS: { name: "Malaysia", flag: "https://flagcdn.com/w20/my.png" },
  MDV: { name: "Maldives", flag: "https://flagcdn.com/w20/mv.png" },
  MLI: { name: "Mali", flag: "https://flagcdn.com/w20/ml.png" },
  MLT: { name: "Malta", flag: "https://flagcdn.com/w20/mt.png" },
  MUS: { name: "Mauritius", flag: "https://flagcdn.com/w20/mu.png" },
  MEX: { name: "Mexico", flag: "https://flagcdn.com/w20/mx.png" },
  MDA: { name: "Moldova", flag: "https://flagcdn.com/w20/md.png" },
  MCO: { name: "Monaco", flag: "https://flagcdn.com/w20/mc.png" },
  MNG: { name: "Mongolia", flag: "https://flagcdn.com/w20/mn.png" },
  MNE: { name: "Montenegro", flag: "https://flagcdn.com/w20/me.png" },
  MAR: { name: "Morocco", flag: "https://flagcdn.com/w20/ma.png" },
  MOZ: { name: "Mozambique", flag: "https://flagcdn.com/w20/mz.png" },
  MMR: { name: "Myanmar", flag: "https://flagcdn.com/w20/mm.png" },
  NAM: { name: "Namibia", flag: "https://flagcdn.com/w20/na.png" },
  NPL: { name: "Nepal", flag: "https://flagcdn.com/w20/np.png" },
  NLD: { name: "Netherlands", flag: "https://flagcdn.com/w20/nl.png" },
  NZL: { name: "New Zealand", flag: "https://flagcdn.com/w20/nz.png" },
  NOR: { name: "Norway", flag: "https://flagcdn.com/w20/no.png" },
  OMN: { name: "Oman", flag: "https://flagcdn.com/w20/om.png" },
  PAK: { name: "Pakistan", flag: "https://flagcdn.com/w20/pk.png" },
  PSE: { name: "Palestine", flag: "https://flagcdn.com/w20/ps.png" },
  PAN: { name: "Panama", flag: "https://flagcdn.com/w20/pa.png" },
  PNG: { name: "Papua New Guinea", flag: "https://flagcdn.com/w20/pg.png" },
  PRY: { name: "Paraguay", flag: "https://flagcdn.com/w20/py.png" },
  PER: { name: "Peru", flag: "https://flagcdn.com/w20/pe.png" },
  PHL: { name: "Philippines", flag: "https://flagcdn.com/w20/ph.png" },
  POL: { name: "Poland", flag: "https://flagcdn.com/w20/pl.png" },
  PRT: { name: "Portugal", flag: "https://flagcdn.com/w20/pt.png" },
  PRI: { name: "Puerto Rico", flag: "https://flagcdn.com/w20/pr.png" },
  QAT: { name: "Qatar", flag: "https://flagcdn.com/w20/qa.png" },
  ROU: { name: "Romania", flag: "https://flagcdn.com/w20/ro.png" },
  RUS: { name: "Russia", flag: "https://flagcdn.com/w20/ru.png" },
  SAU: { name: "Saudi Arabia", flag: "https://flagcdn.com/w20/sa.png" },
  SRB: { name: "Serbia", flag: "https://flagcdn.com/w20/rs.png" },
  SYC: { name: "Seychelles", flag: "https://flagcdn.com/w20/sc.png" },
  SGP: { name: "Singapore", flag: "https://flagcdn.com/w20/sg.png" },
  SVK: { name: "Slovakia", flag: "https://flagcdn.com/w20/sk.png" },
  SVN: { name: "Slovenia", flag: "https://flagcdn.com/w20/si.png" },
  ZAF: { name: "South Africa", flag: "https://flagcdn.com/w20/za.png" },
  KOR: { name: "South Korea", flag: "https://flagcdn.com/w20/kr.png" },
  ESP: { name: "Spain", flag: "https://flagcdn.com/w20/es.png" },
  LKA: { name: "Sri Lanka", flag: "https://flagcdn.com/w20/lk.png" },
  SWE: { name: "Sweden", flag: "https://flagcdn.com/w20/se.png" },
  CHE: { name: "Switzerland", flag: "https://flagcdn.com/w20/ch.png" },
  SYR: { name: "Syria", flag: "https://flagcdn.com/w20/sy.png" },
  TWN: { name: "Taiwan", flag: "https://flagcdn.com/w20/tw.png" },
  TJK: { name: "Tajikistan", flag: "https://flagcdn.com/w20/tj.png" },
  TZA: { name: "Tanzania", flag: "https://flagcdn.com/w20/tz.png" },
  THA: { name: "Thailand", flag: "https://flagcdn.com/w20/th.png" },
  TUR: { name: "Turkey", flag: "https://flagcdn.com/w20/tr.png" },
  UKR: { name: "Ukraine", flag: "https://flagcdn.com/w20/ua.png" },
  ARE: { name: "United Arab Emirates", flag: "https://flagcdn.com/w20/ae.png" },
  GBR: { name: "United Kingdom", flag: "https://flagcdn.com/w20/gb.png" },
  USA: { name: "United States", flag: "https://flagcdn.com/w20/us.png" },
  URY: { name: "Uruguay", flag: "https://flagcdn.com/w20/uy.png" },
  UZB: { name: "Uzbekistan", flag: "https://flagcdn.com/w20/uz.png" },
  VEN: { name: "Venezuela", flag: "https://flagcdn.com/w20/ve.png" },
  VNM: { name: "Vietnam", flag: "https://flagcdn.com/w20/vn.png" },
  ZMB: { name: "Zambia", flag: "https://flagcdn.com/w20/zm.png" },
  ZWE: { name: "Zimbabwe", flag: "https://flagcdn.com/w20/zw.png" },
  ALA: { name: "Åland Islands", flag: "https://flagcdn.com/w20/ax.png" }
};