version: "3.8"

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always

  backend:
    build: ./backend
    env_file:
      - backend/.env
    depends_on:
      - db
    restart: always

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    depends_on:
      - backend
    restart: always

volumes:
  db-data:
  caddy-data:
