version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/campingboka # Kopierer hele prosjektet, inkludert package.json
    working_dir: /campingboka
    command: npm run serve
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: node index.js
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    container_name: campingboka-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
